name: "Create PR to Main"

on:
  push:
    branches:
      - 'develop'

jobs:
  create-pr-to-main:
    name: "Create PR to Main"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Get latest tag
        id: get_latest_tag
        run: |
          # Pega a tag mais recente
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          # Extrai o número da versão (remove o 'v' do início)
          VERSION_NUMBER=${LATEST_TAG#v}
          # Incrementa o patch version
          IFS='.' read -r -a VERSION_PARTS <<< "$VERSION_NUMBER"
          NEW_PATCH_VERSION=$((VERSION_PARTS[2] + 1))
          NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$NEW_PATCH_VERSION"
          
          echo "Current version: $LATEST_TAG"
          echo "New version: v$NEW_VERSION"
          
          echo "NEW_VERSION=v$NEW_VERSION" >> $GITHUB_ENV
          echo "NEW_VERSION_SIMPLE=$NEW_VERSION" >> $GITHUB_ENV

      - name: Check for existing PR
        id: check-pr
        uses: actions/github-script@v6
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: 'develop',
              base: 'main'
            });
            
            if (prs.length > 0) {
              console.log(`Found existing PR #${prs[0].number}`);
              return prs[0].number;
            }
            return 0;

      - name: Create or Update PR
        if: steps.check-pr.outputs.result == 0
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "chore: prepare release v${{ env.NEW_VERSION_SIMPLE }}"
          title: "Release v${{ env.NEW_VERSION_SIMPLE }}: Merge develop to main"
          body: |
            ## Descrição
            Este PR foi criado automaticamente para promover as alterações de develop para main.
            
            ## Mudanças
            - Atualizações de infraestrutura
            - Correções de bugs
            
            ## Versionamento
            Nova versão: **v${{ env.NEW_VERSION_SIMPLE }}**
            
            Para visualizar as alterações completas, consulte o [Changelog](https://github.com/${{ github.repository }}/releases/tag/v${{ env.NEW_VERSION_SIMPLE }}) após o merge.
          branch: "release/$(date +%Y%m%d%H%M%S)"
          base: main
          delete-branch: true

      - name: Update existing PR
        if: steps.check-pr.outputs.result != 0
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          pull-request-number: ${{ steps.check-pr.outputs.result }}
          title: "Release v${{ env.NEW_VERSION_SIMPLE }}: Merge develop to main"
          body: |
            ## Descrição
            Este PR foi atualizado automaticamente com as últimas alterações de develop.
            
            ## Mudanças
            - Atualizações de infraestrutura
            - Correções de bugs
            
            ## Versionamento
            Nova versão: **v${{ env.NEW_VERSION_SIMPLE }}**
            
            Para visualizar as alterações completas, consulte o [Changelog](https://github.com/${{ github.repository }}/releases/tag/v${{ env.NEW_VERSION_SIMPLE }}) após o merge.