name: "Feature Validation and PR to Develop"

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'develop'

jobs:
  terraform-validate:
    name: "Terraform Validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate -no-color

  create-pr-to-develop:
    name: "Create PR to Develop"
    needs: terraform-validate
    if: startsWith(github.ref, 'refs/heads/feature/') && github.event_name == 'push' && success()
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "chore: merge changes from ${{ github.ref_name }}"
          title: "Merge ${{ github.ref_name }} to develop"
          body: |
            This PR was automatically created by GitHub Actions.
            
            Changes from feature branch: `${{ github.ref_name }}`
            
            **Reviewers:** Please review the changes and approve if everything looks good.
            
            **Note:** This PR was automatically generated by GitHub Actions.
          base: develop
          branch: merge-${{ github.ref_name }}
          delete-branch: true
          draft: false
          labels: automated-pr,terraform