name: "Feature Validation and PR to Develop"

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - 'develop'

jobs:
  terraform-validate:
    name: "Terraform Validate"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate -no-color

  create-pr-to-develop:
    name: "Create PR to Develop"
    needs: terraform-validate
    if: startsWith(github.ref, 'refs/heads/feature/') && github.event_name == 'push' && success()
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Create PR using GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          REPO: ${{ github.repository }}
          HEAD_REF: ${{ github.ref_name }}
        run: |
          # Extrai o nome da feature do branch
          FEATURE_NAME="${HEAD_REF#feature/}"
          
          # Cria o PR usando a API do GitHub
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/pulls" \
            -d '{
            "title": "[Feature] '"$FEATURE_NAME"'",
            "body": "PR criado automaticamente da feature '"$HEAD_REF"' para develop",
            "head": "'"$HEAD_REF"'",
            "base": "develop"
          }'