name: "Apply to Production"

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    # Só executa quando o evento é um push para main, não em PRs
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    defaults:
      run:
        working-directory: ./infra

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false

#      - name: Terraform Apply
#        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#        run: |
#          # Obter a versão atual
#          VERSION=$(cat VERSION || echo "0.1.0")
#          terraform apply -auto-approve -input=false
#          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update PR with Apply Status
        if: github.event_name == 'pull_request'
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.pull_request.head.sha }}" \
            -d '{
              "state": "success",
              "description": "Terraform apply successful",
              "context": "terraform-apply"
            }'

  notify-success:
    name: "Notify Success"
    needs: [terraform-apply, versioning]
    if: always() && github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Send success notification
        if: success()
        run: |
          echo "Terraform apply executado com sucesso em produção! Versão: ${{ env.RELEASE_VERSION }}"
          # Adicione aqui notificações adicionais (email, Slack, etc.)

      - name: Send failure notification
        if: failure()
        run: |
          echo "ERRO: Falha ao executar Terraform apply em produção! Versão: ${{ env.RELEASE_VERSION }}"
          # Adicione aqui notificações de erro